# Generated by Django 4.2.7 on 2023-12-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bought_cars',
            field=models.ManyToManyField(to='cars.carsmodel'),
        ),
    ]
